version: '3.9'
services:
  web:
    build: .
    ports:
     - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
    depends_on:
      - db
    entrypoint: ["/entrypoint.sh"]
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      APP_PORT: ${APP_PORT}
      SERVICE_WORKERS: ${SERVICE_WORKERS}
      DB_HOST: "db"
  db:
    image: "postgres:16-alpine3.20"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - ${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
volumes:
  postgres_data: